### ISSUE TITLE
При введении значения в поле InitialBalance меньше чем в Min не срабатывает исключение

### ISSUE THREAD

**Issue by ShilovaIrina** [ktshva/javaqa-team-diplom-2#10]
# Описание
При введении значения в поле InitialBalance значение меньше допустимого не срабатывает исключение вида IllegalArgumentException

# Локация дефекта
https://github.com/ktshva/javaqa-team-diplom-2/blob/f83616db72a203f7c100d029ac0f7a64e5a5cf42/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения

1.  Открыть [код программы](https://github.com/ktshva/javaqa-team-diplom-2/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект SavingAccount account 
3. Выставить значение переменной `wasException` = false
4. Добавить конструкцию try-catch
5. Выставить значение поля `Initialbalance` в 200 рублей
6. Выставить значение поля `MinBalance` в  500 рублей
7.  Выставить значение поля `MaxBalance` в 10000 рублей
8.  Выставить значение поля `rate` 10%
9.  Запустить тест

*Ожидаемый результат:* срабатывает перехват исключения, тест проходит, мы получаем вывод ошибки о недопустимых значениях в поле
*Фактический результат:* тест падает, исключение не обрабатывается. 

# Тест
https://github.com/ktshva/javaqa-team-diplom-2/blob/f83616db72a203f7c100d029ac0f7a64e5a5cf42/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L102

# Скриншот
![image](https://github.com/ktshva/javaqa-team-diplom-2/assets/152436584/044d1f3b-bdcd-47f7-9bf0-dadfb6cfa490)

# Окружение
* **Операционная система:** Windows 10 
* **IDE:** IntelliJ IDEA Community Edition 2023.3
*  **Java:** Amazon Corretto 11

**Comment by ktshva** [comment]
исправлено dfd0a483641e1c261ce0960ef89853629d62fb14
