### ISSUE TITLE
При совершении покупки остаток на счету не соответствует MinBalance

### ISSUE THREAD

**Issue by ShilovaIrina** [ktshva/javaqa-team-diplom-2#13]
# Описание
При совершении покупки остаток по счету не соответствует значению допустимому для поля MinBalance 

# Локация дефекта
https://github.com/ktshva/javaqa-team-diplom-2/blob/f83616db72a203f7c100d029ac0f7a64e5a5cf42/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения

1.  Открыть [код программы](https://github.com/ktshva/javaqa-team-diplom-2/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект SavingAccount account 
3. Выставить значение поля `Initialbalance` в 10000 рублей
4. Выставить значение поля `MinBalance` в 5000 рублей
5. Выставить значение поля `MaxBalance` в 1000000 рублей
6. Выставить значение поля `rate` 10%
7. Задаем переменную `correctOperation` с методом account
8.  Задаем переменной значение 7000 рублей
9. Запустить тест

*Ожидаемый результат:* тест проходит, операция по покупке не проходит, счет остается без изменений
*Фактический результат:* тест не проходит, мы получает остаток на счету 3000

# Тест
https://github.com/ktshva/javaqa-team-diplom-2/blob/f83616db72a203f7c100d029ac0f7a64e5a5cf42/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L184

# Скриншот
![image](https://github.com/ktshva/javaqa-team-diplom-2/assets/152436584/a271221f-64dc-4732-9ad4-48885f43620e)

# Окружение
* **Операционная система:** Windows 10 
* **IDE:** IntelliJ IDEA Community Edition 2023.3
*  **Java:** Amazon Corretto 11

**Comment by ktshva** [comment]
исправлено dfd0a483641e1c261ce0960ef89853629d62fb14
