### ISSUE TITLE
При пополнении счета операция не проходит

### ISSUE THREAD

**Issue by ShilovaIrina** [ktshva/javaqa-team-diplom-2#14]
# Описание
При пополнении счета операция не проходит

# Локация дефекта
https://github.com/ktshva/javaqa-team-diplom-2/blob/f83616db72a203f7c100d029ac0f7a64e5a5cf42/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения

1.  Открыть [код программы](https://github.com/ktshva/javaqa-team-diplom-2/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект SavingAccount account 
3. Выставить значение поля `Initialbalance` в 2000 рублей
4. Выставить значение поля `MinBalance` в 1000 рублей
5. Выставить значение поля `MaxBalance` в 10000 рублей
6. Выставить значение поля `rate` 5%
7. Задаем переменную `correctOperation` с методом account
8.  Задаем переменной значение 3000 рублей
9. Запустить тест

*Ожидаемый результат:* тест проходит, операция по пополнению проходит, на счету у нас 5000
*Фактический результат:* тест не проходит, операция по полнению не выполнена, мы получает остаток по счету без изменений

# Тест
https://github.com/ktshva/javaqa-team-diplom-2/blob/f83616db72a203f7c100d029ac0f7a64e5a5cf42/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L203

# Скриншот
![image](https://github.com/ktshva/javaqa-team-diplom-2/assets/152436584/9ba08d20-65c0-4133-b426-da53bd2dd261)

# Окружение
* **Операционная система:** Windows 10 
* **IDE:** IntelliJ IDEA Community Edition 2023.3
*  **Java:** Amazon Corretto 11

**Comment by ktshva** [comment]
исправлено dfd0a483641e1c261ce0960ef89853629d62fb14
